### ISSUE TITLE
Add support for multiple entity managers

### ISSUE THREAD

**Issue by ranpafin** [facile-it/paraunit-testcase#4]
It's not uncommon for a doctrine project to declare multiple entity managers, often making use of different connections.

I would expect the testcase to properly isolate all the entity managers and not only the default one.

**Comment by Jean85** [comment]
How would you do that?
Also, I would like to leave the default `getEm()` helper: let's not ruin BC!

**Comment by ranpafin** [comment]
I would bet there is some kind of way to get all configured entity managers.
If all else fail reading the doctrine config it's still an option.

Once we got them all we can just mimic the actual transaction/container switch for all the ems.

---

```
getEm()
```

could accept an optional 'name' parameter like:

```
getEm($entityManagerName)
```

if not provided will return the default one. 

Make sense?

**Comment by fntlnz** [comment]
This sounds reasonable to me, it won't lead to any BC while giving us the flexibility to use multiple entity managers.

**Comment by ranpafin** [comment]
Fixed with commit 83fccb0f479c2ba7075aa4a7358012dcf604b405
