### ISSUE TITLE
ParaunitWebTestCase with enabled profiler doesn't work correctly

### ISSUE THREAD

**Issue by marrek13** [facile-it/paraunit-testcase#7]
Hello,

I wanted to test if a mail is sent after the object is added to the database, but apparently the profiler doesn't save any data when I use that class. I receive the "X-Debug-Token", but the profiler storage is empty, and the folder in cache is empty too. When I try to get profiler data using that token, I receive "NULL".

When I made similar test, that uses straight the WebTestCase from Liip, the profiler is creating files, and everything is working fine.

I'm pretty new in writing tests, so it is possible, that I'm doing something wrong, but I can't manage to make it work. Of course the profiler is enabled in config_test.yml, and I use the enableProfiler() method before the request.

**Comment by Jean85** [comment]
Hi @marrek13, and thanks for raising this issue!

Unfortunately (for me!) it's not your fault, the client has this issue with this testcase. I tried it in the past and it didn't work. I'll try to look into it to see if there is any possible solution, but the main issue is that the Client spins up a different kernel, and that my hamper how the profiler works.

**Comment by Jean85** [comment]
I should have fixed it!

Can you try this requiring the package as `dev-master`? If it works, I will tag it!

**Comment by marrek13** [comment]
It is working! Thank you for a quick fix! Great job :)
